name: Send Daily IT News to Slack

on:
  # 매일 아침 9시(한국 시간 기준)에 실행
  schedule:
    - cron: '0 0 * * 1-5' # UTC 기준 00:00 (KST 09:00)
  # 수동으로 직접 실행할 수도 있도록 workflow_dispatch 추가
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to send news
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: python main.py
